name: Auto_Pickup
version: 2.7
main: me.MnMaxon.AutoPickup.Main
commands:
  AutoPickup:
    description: Reloads the plugin
    aliases: [ap]
  AutoPickupToggle:
    description: Toggles autopickup
    aliases: [apt, aptoggle, toggleap, toggleautopickup]
  AutoSmelt:
    description: AutoSmelts your inventory
    aliases: [as]
  AutoBlock:
    description: Changes all of your ingots to blocks
    aliases: [ab]